# 请配置你所需要的套装、Cost、以及其对应属性，将不需要的属性删除。
# 4COST_ECHO优先级高于4COST，4COST_ECHO内的声骸可自行增减，没名字的默认按4COST内的配置执行
EchoLockConfig:
  凝夜白霜:
    1COST: [ "攻击", "防御", "生命" ]
    3COST: [ "攻击", "防御", "生命", "共鸣效率", "冷凝伤害加成", "热熔伤害加成", "导电伤害加成", "气动伤害加成", "衍射伤害加成", "湮灭伤害加成" ]
    4COST: [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ]
    4COST_ECHO: {
      "辉萤军势": [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ],
    }
  熔山裂谷:
    1COST: [ "攻击", "防御", "生命" ]
    3COST: [ "攻击", "防御", "生命", "共鸣效率", "冷凝伤害加成", "热熔伤害加成", "导电伤害加成", "气动伤害加成", "衍射伤害加成", "湮灭伤害加成" ]
    4COST: [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ]
    4COST_ECHO: {
      "燎照之骑": [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ],
    }
  彻空冥雷:
    1COST: [ "攻击", "防御", "生命" ]
    3COST: [ "攻击", "防御", "生命", "共鸣效率", "冷凝伤害加成", "热熔伤害加成", "导电伤害加成", "气动伤害加成", "衍射伤害加成", "湮灭伤害加成" ]
    4COST: [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ]
    4COST_ECHO: {
      "云闪之鳞": [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ],
      "朔雷之鳞": [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ],
    }
  啸谷长风:
    1COST: [ "攻击", "防御", "生命" ]
    3COST: [ "攻击", "防御", "生命", "共鸣效率", "冷凝伤害加成", "热熔伤害加成", "导电伤害加成", "气动伤害加成", "衍射伤害加成", "湮灭伤害加成" ]
    4COST: [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ]
    4COST_ECHO: {
      "飞廉之猩": [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ],
    }
  浮星祛暗:
    1COST: [ "攻击", "防御", "生命" ]
    3COST: [ "攻击", "防御", "生命", "共鸣效率", "冷凝伤害加成", "热熔伤害加成", "导电伤害加成", "气动伤害加成", "衍射伤害加成", "湮灭伤害加成" ]
    4COST: [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ]
    4COST_ECHO: {
      "角": [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ],
      "哀声鸷": [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ],
    }
  沉日劫明:
    1COST: [ "攻击", "防御", "生命" ]
    3COST: [ "攻击", "防御", "生命", "共鸣效率", "冷凝伤害加成", "热熔伤害加成", "导电伤害加成", "气动伤害加成", "衍射伤害加成", "湮灭伤害加成" ]
    4COST: [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ]
    4COST_ECHO: {
      "无妄者": [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ],
      "无冠者": [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ],
    }
  隐世回光:
    1COST: [ "攻击", "防御", "生命" ]
    3COST: [ "攻击", "防御", "生命", "共鸣效率", "冷凝伤害加成", "热熔伤害加成", "导电伤害加成", "气动伤害加成", "衍射伤害加成", "湮灭伤害加成" ]
    4COST: [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ]
    4COST_ECHO: {
      "无归的谬误": [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ],
      "鸣钟之龟": [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ],
    }
  轻云出月:
    1COST: [ "攻击", "防御", "生命" ]
    3COST: [ "攻击", "防御", "生命", "共鸣效率", "冷凝伤害加成", "热熔伤害加成", "导电伤害加成", "气动伤害加成", "衍射伤害加成", "湮灭伤害加成" ]
    4COST: [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ]
    4COST_ECHO: {
      "鸣钟之龟": [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ],
      "无常凶鹭": [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ],
    }
  不绝余音:
    1COST: [ "攻击", "防御", "生命" ]
    3COST: [ "攻击", "防御", "生命", "共鸣效率", "冷凝伤害加成", "热熔伤害加成", "导电伤害加成", "气动伤害加成", "衍射伤害加成", "湮灭伤害加成" ]
    4COST: [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ]
    4COST_ECHO: {
      "聚械机偶": [ "攻击", "防御", "生命", "治疗效果加成", "暴击", "暴击伤害" ],
    }